kind: Deployment
apiVersion: apps/v1
metadata:
  name: my-cluster-entity-operator
  namespace: kafka
  selfLink: /apis/apps/v1/namespaces/kafka/deployments/my-cluster-entity-operator
  uid: b63234b4-8931-4864-bd50-8f8359753d9b
  resourceVersion: '10687743'
  generation: 1
  creationTimestamp: '2020-09-11T00:20:21Z'
  labels:
    app.kubernetes.io/instance: my-cluster
    app.kubernetes.io/managed-by: strimzi-cluster-operator
    app.kubernetes.io/name: entity-operator
    app.kubernetes.io/part-of: strimzi-my-cluster
    strimzi.io/cluster: my-cluster
    strimzi.io/kind: Kafka
    strimzi.io/name: my-cluster-entity-operator
  annotations:
    deployment.kubernetes.io/revision: '1'
  ownerReferences:
    - apiVersion: kafka.strimzi.io/v1beta1
      kind: Kafka
      name: my-cluster
      uid: 26c4df15-9f69-4982-97ac-96d931e81358
      controller: false
      blockOwnerDeletion: false
spec:
  replicas: 1
  selector:
    matchLabels:
      strimzi.io/cluster: my-cluster
      strimzi.io/kind: Kafka
      strimzi.io/name: my-cluster-entity-operator
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: my-cluster
        app.kubernetes.io/managed-by: strimzi-cluster-operator
        app.kubernetes.io/name: entity-operator
        app.kubernetes.io/part-of: strimzi-my-cluster
        strimzi.io/cluster: my-cluster
        strimzi.io/kind: Kafka
        strimzi.io/name: my-cluster-entity-operator
      annotations:
        strimzi.io/clients-ca-cert-generation: '0'
        strimzi.io/cluster-ca-cert-generation: '0'
    spec:
      volumes:
        - name: entity-topic-operator-metrics-and-logging
          configMap:
            name: my-cluster-entity-topic-operator-config
            defaultMode: 420
        - name: entity-user-operator-metrics-and-logging
          configMap:
            name: my-cluster-entity-user-operator-config
            defaultMode: 420
        - name: eo-certs
          secret:
            secretName: my-cluster-entity-operator-certs
            defaultMode: 292
        - name: cluster-ca-certs
          secret:
            secretName: my-cluster-cluster-ca-cert
            defaultMode: 292
      containers:
        - name: topic-operator
          image: 'strimzi/operator:0.19.0'
          args:
            - /opt/strimzi/bin/topic_operator_run.sh
          ports:
            - name: healthcheck
              containerPort: 8080
              protocol: TCP
          env:
            - name: STRIMZI_RESOURCE_LABELS
              value: strimzi.io/cluster=my-cluster
            - name: STRIMZI_KAFKA_BOOTSTRAP_SERVERS
              value: 'my-cluster-kafka-bootstrap:9091'
            - name: STRIMZI_ZOOKEEPER_CONNECT
              value: 'localhost:2181'
            - name: STRIMZI_NAMESPACE
              value: kafka
            - name: STRIMZI_FULL_RECONCILIATION_INTERVAL_MS
              value: '90000'
            - name: STRIMZI_ZOOKEEPER_SESSION_TIMEOUT_MS
              value: '20000'
            - name: STRIMZI_TOPIC_METADATA_MAX_ATTEMPTS
              value: '6'
            - name: STRIMZI_TLS_ENABLED
              value: 'true'
            - name: STRIMZI_GC_LOG_ENABLED
              value: 'false'
          resources: {}
          volumeMounts:
            - name: entity-topic-operator-metrics-and-logging
              mountPath: /opt/topic-operator/custom-config/
            - name: eo-certs
              mountPath: /etc/tls-sidecar/eo-certs/
            - name: cluster-ca-certs
              mountPath: /etc/tls-sidecar/cluster-ca-certs/
          livenessProbe:
            httpGet:
              path: /healthy
              port: healthcheck
              scheme: HTTP
            initialDelaySeconds: 10
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /ready
              port: healthcheck
              scheme: HTTP
            initialDelaySeconds: 10
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
        - name: user-operator
          image: 'strimzi/operator:0.19.0'
          args:
            - /opt/strimzi/bin/user_operator_run.sh
          ports:
            - name: healthcheck
              containerPort: 8081
              protocol: TCP
          env:
            - name: STRIMZI_ZOOKEEPER_CONNECT
              value: 'localhost:2181'
            - name: STRIMZI_KAFKA_BOOTSTRAP_SERVERS
              value: 'my-cluster-kafka-bootstrap:9091'
            - name: STRIMZI_NAMESPACE
              value: kafka
            - name: STRIMZI_LABELS
              value: strimzi.io/cluster=my-cluster
            - name: STRIMZI_FULL_RECONCILIATION_INTERVAL_MS
              value: '120000'
            - name: STRIMZI_ZOOKEEPER_SESSION_TIMEOUT_MS
              value: '6000'
            - name: STRIMZI_CA_KEY_NAME
              value: my-cluster-clients-ca
            - name: STRIMZI_CA_CERT_NAME
              value: my-cluster-clients-ca-cert
            - name: STRIMZI_CA_NAMESPACE
              value: kafka
            - name: STRIMZI_CA_VALIDITY
              value: '365'
            - name: STRIMZI_CA_RENEWAL
              value: '30'
            - name: STRIMZI_CLUSTER_CA_CERT_SECRET_NAME
              value: my-cluster-cluster-ca-cert
            - name: STRIMZI_EO_KEY_SECRET_NAME
              value: my-cluster-entity-operator-certs
            - name: STRIMZI_GC_LOG_ENABLED
              value: 'false'
          resources: {}
          volumeMounts:
            - name: entity-user-operator-metrics-and-logging
              mountPath: /opt/user-operator/custom-config/
            - name: eo-certs
              mountPath: /etc/tls-sidecar/eo-certs/
            - name: cluster-ca-certs
              mountPath: /etc/tls-sidecar/cluster-ca-certs/
          livenessProbe:
            httpGet:
              path: /healthy
              port: healthcheck
              scheme: HTTP
            initialDelaySeconds: 10
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /ready
              port: healthcheck
              scheme: HTTP
            initialDelaySeconds: 10
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
        - name: tls-sidecar
          image: 'strimzi/kafka:0.19.0-kafka-2.5.0'
          command:
            - /opt/stunnel/entity_operator_stunnel_run.sh
          env:
            - name: TLS_SIDECAR_LOG_LEVEL
              value: notice
            - name: STRIMZI_ZOOKEEPER_CONNECT
              value: 'my-cluster-zookeeper-client:2181'
          resources: {}
          volumeMounts:
            - name: eo-certs
              mountPath: /etc/tls-sidecar/eo-certs/
            - name: cluster-ca-certs
              mountPath: /etc/tls-sidecar/cluster-ca-certs/
          livenessProbe:
            exec:
              command:
                - /opt/stunnel/stunnel_healthcheck.sh
                - '2181'
            initialDelaySeconds: 15
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            exec:
              command:
                - /opt/stunnel/stunnel_healthcheck.sh
                - '2181'
            initialDelaySeconds: 15
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          lifecycle:
            preStop:
              exec:
                command:
                  - /opt/stunnel/entity_operator_stunnel_pre_stop.sh
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      serviceAccountName: my-cluster-entity-operator
      serviceAccount: my-cluster-entity-operator
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: Recreate
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
status:
  observedGeneration: 1
  replicas: 1
  updatedReplicas: 1
  readyReplicas: 1
  availableReplicas: 1
  conditions:
    - type: Available
      status: 'True'
      lastUpdateTime: '2020-09-11T00:20:42Z'
      lastTransitionTime: '2020-09-11T00:20:42Z'
      reason: MinimumReplicasAvailable
      message: Deployment has minimum availability.
    - type: Progressing
      status: 'True'
      lastUpdateTime: '2020-09-11T00:20:42Z'
      lastTransitionTime: '2020-09-11T00:20:21Z'
      reason: NewReplicaSetAvailable
      message: >-
        ReplicaSet "my-cluster-entity-operator-77c689b986" has successfully
        progressed.
